Resources:
  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: postId
          AttributeType: S
        - AttributeName: variant
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: postId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: userId-variant-index
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: variant
            KeyType: RANGE
          Projection:
            ProjectionType: ALL