Resources:
  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.profilesTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: activityId
          AttributeType: N
        - AttributeName: variant
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: activityId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
            - accessKey
            ProjectionType: INCLUDE
        - IndexName: userId-variant-index
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: variant
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST